### ISSUE TITLE
Non-interactive usage broken

### ISSUE THREAD

**Issue by port19x** [pystardust/ani-cli#1104]
**Metadata (please complete the following information)**
Version: 4.2.2
OS: Arch Linux
Shell: zsh
Anime: n/a

**Describe the bug**

We ought to support completely non-interactive invokation.
Right now after non interactive startup and after exiting the playback, we still have the main menu.

**Steps To Reproduce**

1. `ani-cli -S 1 -e 1 flcl`
2. menu pops up
3. :(

**Expected behavior**
support [downstream](https://github.com/z411/trackma/issues/637)

**Comment by imsamuka** [comment]
For this, it would be probably better to have a `non-interactive` flag, which deactivates the menu after a episode is done and doesn't run the `rofi` as a fallback either.

The current behavior is quite satisfactory in my opinion

**Comment by imsamuka** [comment]
In fact, it would be probably better to not specify `-S 1` by default, only when rofi is not installed, because the user can select the correct anime to watch. 

This is a deal breaker for me, personally I almost never used this script that i made, because it most often fails to select the correct anime (and the poor bit rate)

**Comment by port19x** [comment]
Was actually fixed in #1107
