### ISSUE TITLE
Test against ShellCheck

### ISSUE THREAD

**Issue by SkyyySi** [pystardust/ani-cli#122]
ShellCheck is a linter (i.e. a tool to find issues) for shell scripts. It can be used as a linter in many editors (including VScode and micro), as a GitHub action (which will automatically run it against your code on each push), as a standalone command line application or even from the web: https://www.shellcheck.net/

I tested this script against it and it seems to have a few dozen issues.

**Comment by Dink4n** [comment]
It's just warnings and info

**Comment by ura43** [comment]
Even if it was just warnings and info, it would be a worthwhile investment of time, due to the increased code quality and maintainability that comes with it.
But it can also help us follow contribution guidelines by testing for posix compliance.
I volunteer to implement the github action and adapt the initial changes.

**Comment by ura43** [comment]
Our formatting of strings triggers false positives for SC1087

**Comment by ura43** [comment]
That is 12x SC1087 and 9x 2059 btw
