### ISSUE TITLE
Not Installing on Fedora 40 from Repo and doesn't run from Source either

### ISSUE THREAD

**Issue by tegaidogun** [pystardust/ani-cli#1222]
Version: [Latest]
OS: Fedora Linux 40
Shell: fish
Anime: `N/A`

**Describe the bug**
No repository for Fedora, and setting it up on my system didn't work either way as the `ani-cli` ran but the episode didn't start.

**Steps To Reproduce**

1. Run `sudo dnf copr enable derisis13/ani-cli
                           sudo dnf install ani-cli`.
                           
**Expected behavior**
Installing `ani-cli` should work

**Screenshots**
![Screenshot from 2023-09-30 23-36-08](https://github.com/pystardust/ani-cli/assets/63559796/ed8d7ef1-9793-47ae-bf5a-f0248c8ea767)
07557b4b29.png)

**Comment by Sarvasv-0** [comment]
## Short Answer

you can use this until the error is fixed

1. download the latest ani-cli release at [releases](https://github.com/pystardust/ani-cli/releases/latest)
![Screenshot from 2023-10-02 21-09-29](https://github.com/pystardust/ani-cli/assets/81177923/03e95c90-0e4d-49a5-bc56-82489a93005b)

2. navigate to the folder where you have downloaded the file

3. open terminal app
4. copy the file to bin folder by pasting this in the terminal
```bash
sudo cp ./ani-cli /usr/local/bin/
```
5. restart the terminal emulator/app
6. enjoy!


## Long Answer

The error is occurring because the ani-cli package Fedora 40 is not yet added in the repository. This is one of the reason I resist to Update my Distro quickly (I use fedora 38), you can fix this by installing the fedora 38 package by this method [on unix stackexchange](https://unix.stackexchange.com/questions/269763/how-to-install-packages-for-old-version-of-fedora) but since it is very old, I don't recommend using it.

---

> Ending the discussion, I just want to tell you that you can use the above method

**Comment by Derisis13** [comment]
Is there a Fedora 40? I don't see a download link on the website (torrent.fedoraproject.org) nor is there a chroot to it on copr.
I enabled Fedora 39 as a chroot but until 40 is added to copr I can't build you a package. I think you can still get the source .rpm from the repo and build yourself a package if you wish to... Otherwise the packages should be near identical (unless dnf/yum changed between 40 and 38 significantly) it's a really simple build. But to be safe I'd recommend the source installation too.

I've submitted v4.6.1 for rebuild, it should appear in the new repos (I also added Suse 15.5) hopefully

**Comment by tegaidogun** [comment]
Oh, it seems to be arising from the lack of OpenH264 support on that alpha build of Fedora, Apologies for the delay i response. 

I'm closing this issue.

**Comment by Derisis13** [comment]
> Oh, it seems to be arising from the lack of OpenH264 support on that alpha build of Fedora
Can you elaborate? Do we need an extra dependency for the Fedora 40 package?

**Comment by tegaidogun** [comment]
Oh no, as of the last time I check the Alpha Build of Fedora 40 has no OpenH264 support on both the free and non-free repos.

**Comment by Derisis13** [comment]
Well mpv and vlc already requires you to install rpmsphere-free and I assume fedora40 will place it there just like many other "questionable" and "contravertial" software
