### ISSUE TITLE
Git bash works fine without Windows Terminal

### ISSUE THREAD

**Issue by catsanddo** [pystardust/ani-cli#1239]
Less of a feature and more of a documentation oversight.
The docs say that `fzf` does not work in git-bash's default terminal. This is kind of true, but it DOES work in regular `cmd.exe`. If you run bash directly via `bash.exe` (located in `Git\bin`) or from the included `git-cmd.exe` everything work just fine.

Using Windows terminal is just overkill here. Recommending that people just use `git-cmd.exe` is the simplest solution and is far easier to get working.

For the record powershell's terminal and Alacritty work great too.

**Comment by Derisis13** [comment]
It's interesting, I'm open for simplifications. Our goal with the windows instructions is that the median windows user should be able to follow them. So I'm open for simplifications, but I'll have to try git-cmd to see how well it handles.
I've chosen the windows terminal, since many power users have it already, and that was the first terminal I found to work with fzf. It's an OK terminal but if I can get rid of the "complicated" install procedure it'd be great.
