### ISSUE TITLE
Episode Download does not work 

### ISSUE THREAD

**Issue by rakusan2** [pystardust/ani-cli#1325]
**Metadata (please complete the following information)**
Version: 4.8.5
OS: Windows 11
Shell: Powershell 7.4.2
Anime: Maou Gakuin no Futekigousha

**Describe the bug**
Downloading is broken.
Playing works

![image](https://github.com/pystardust/ani-cli/assets/10575235/13363f7f-a76f-4709-8490-fd006cc537f0)

if the `-d 1` is removed, 2 seasons of the anime get found

**Steps To Reproduce**

1. Run `ani-cli "Maou Gakuin no Fute" -d 1`

**Expected behavior**
Downloading should work

**Comment by ykhan21** [comment]
What is the `1` for? Do you want to select the first search result for `Maou Gakuin no Fute`?
If so, try `ani-cli "Maou Gakuin no Fute" -d -S 1` to auto-select the first search result.
Otherwise, try `ani-cli "Maou Gakuin no Fute" -d`.
If you want to download a range, try `ani-cli "Maou Gakuin no Fute" -d -e 2-4`. This downloads episodes 2 through 4.
All three of these commands work for me on Windows 11.

**Comment by rakusan2** [comment]
Sorry looks like I was drunk that day.
I was missing `ani-cli "Maou Gakuin no Fute" -d -e 1` 
I was missing the `-e`

I usually then select the season manually.

Everything works now
