### ISSUE TITLE
ani-cli command doesn't see ani-cli app file (No such file or directory)

### ISSUE THREAD

**Issue by mozkohor** [pystardust/ani-cli#1352]
**Metadata (please complete the following information)**
Version: 4.8
OS: Windows 11

**Describe the bug**
Running `ani-cli` returns with error saying that the ani-cli file doesn't exist (screenshot for more context).

**Steps To Reproduce**

1. Run `ani-cli`

**Expected behavior**
It should run ani-cli

**Screenshots (if applicable; you can just drag the image onto github. remove the following line if not needed)**
![image](https://github.com/pystardust/ani-cli/assets/84287967/c7ac7b49-45d7-452d-94c9-346684cf5fe0)
![image](https://github.com/pystardust/ani-cli/assets/84287967/7a880593-6610-45f2-be8b-a21cad3d8d68)

**Comment by ykhan21** [comment]
@mozkohor and @amad3us47, replace `@bash` with `@"C:\Users\<user>\scoop\apps\git\current\bin\bash.exe"` in the ani-cli.cmd file if you want to run it with powershell.

* This assumes you install git with scoop. If you installed git with the installer, replace `@bash` with `@"C:\Program Files\Git\bin\bash.exe"`

The issue is that the `scoop/shims/ani-cli.cmd` shim that gets called when you enter `ani-cli` in powershell calls wsl bash. Git bash doesn't have this problem because git bash comes with a normal bash shell which gets invoked instead of the wsl bash.

There is a PR to fix this on scoop's side: https://github.com/ScoopInstaller/Extras/pull/13342, which automatically does the `wsl bash` -> `git for windows' bash` replacement.
