### ISSUE TITLE
--skip-title does not work properly

### ISSUE THREAD

**Issue by supremecmdr** [pystardust/ani-cli#1388]
**Metadata (please complete the following information)**
Version: 4.8.11
OS: Linux Debian 12
Shell: dash
Anime: Another (Original title: Anazâ / アナザー)

**Describe the bug**
I am trying to see Another by a friend suggestion, and as the title interferes a lot with Isekai thought to use the --skip-title "Isekai" to filter better but it still returns the same results without any change. I tried every variation I could think of, change the parameters order, use quote or single quotes or not at all. 
I had success in the end by using the japanese lettered title. which return a lot fewer (6) and among it the "Another" I was looking for.

**Steps To Reproduce**

1. Run ani-cli another --skip-title "isekai"
2. Despair as the same 40 results fill the list.

**Expected behavior**
should find any with English word Another but filter out the Isekai

**Comment by port19x** [comment]
The problem here is a misunderstanding of what `--skip-title` is actually supposed to do.
`--skip-title` does not do any filtering.
What `--skip-title` does is it supplies [ani-skip](TODO) with an explicit title, for cases where allanime and ani-skip have different titles for the same anime.

Searching for the japanese name is one workaround.
The release year can also sometimes be in a generic anime title.

The bug here is that you can't find Another when searching for it, I'll see if I can reproduce this later

**Comment by supremecmdr** [comment]
My bad, thank you for pointing this out. Would be nice to be able to filter somehow though.

**Comment by port19x** [comment]
Can reproduce, but not sure how this could be fixed.
Appending the release year (2012) did not help

**Comment by port19x** [comment]
I don't think I can or want to do anything about this, but thanks for reporting
