### ISSUE TITLE
Can we use the aria2 downloader?

### ISSUE THREAD

**Issue by Reaper176** [pystardust/ani-cli#165]
So I was just wondering if it is possible to change the downloader to aria2?

This question is spared on by my lack of knowledge. XD

I have symlinked youtube-dl to yt-dlp, and have no idea if that is enough.

**Comment by TheGlockMisc** [comment]
Its possible to download streams in Aria2 though its so complex.
as a noob ffmpeg is only my best option when downloading streams.

**Comment by ura43** [comment]
Possible, yes.
Useful or recommended, no

**Comment by CoolnsX** [comment]
aria2c --referer "$embedded_video_url" "$play_link" --dir=$HOME/Desktop -o "${anime_id}-${episode}.mp4"

Note:-
--dir option will choose any directory you specify for download..
--referer argument is optional, but I put it there just to be on safe side..

**Comment by ura43** [comment]
@CoolnsX it seems like replacing ffmpeg with aria2 would be a massive enhancement, even enabling a torrent mode in the future.
We currently only use ffmpeg on one line to facilitate downloading: 
`ffmpeg -i "$play_link" -c copy "${anime_id}-${episode}.mkv" >/dev/null 2>&1 &&`
I only learned about aria2s existance yesterday, so if you could list some pro's and con's of a potential switch that would be awesome

**Comment by ura43** [comment]
It gets some praise in the comments [here](https://www.reddit.com/r/linuxmemes/comments/rna7wu/chose_one/)

**Comment by CoolnsX** [comment]
Aria2c is best cli download manager IMO..
Its features:-
1. Parallel downloading of a file (if servers allows it, it can speed up ur downloads).. also previous gogoanime download links were slower around 300-400 kB/s... There I used aria and I always got around 3-5 MB/s... Since then I am using aria2c in my every script for downloading...

2. Torrent downloading.. yes it can download torrents to... I used it in downloading latest anime episodes from (subsplease.org)(also made a script for it)... which gives magnet link...

3.  You can even pass referer link... If the download link requires it... As in our case...

**Comment by ura43** [comment]
Okay, we should definitely leverage aria2 in some capacity then. 
If I recall correctly, it could theoretically even replace curl.
Its not like we use some overly complex curl functionality so that might work too.
Are you interested in working on a PR?

**Comment by RaynardGerraldo** [comment]
wow, this is actually nice, what makes it even better if we use

`aria2c "$play_link" -d "${anime_id}-${episode}.mkv" --download-result=hide`

this will also give us progress status and solves #109 #113

I can open a pr for this but maybe OP or @CoolnsX can contribute by doing the pr

**Comment by ura43** [comment]
A builtin progress status without external dependency? 
Sign me up :smile: 

Let's see if @CoolnsX is up to the task

**Comment by CoolnsX** [comment]
Already applied pull request...

**Comment by ura43** [comment]
Not really, but I'd like to merge some other things first since this introduces a new dependency.
Can you investigate if migrating our curl usage to aria2 as well would be sensible?
I like a low sum of dependencies

**Comment by Dink4n** [comment]
> Can you investigate if migrating our curl usage to aria2 as well would be sensible?

`aria2` is an utility for downloading files

> I like a low sum of dependencies

We can use `curl` to download files. It comes with a progress bar.

**Comment by ura43** [comment]
Good catch  @Dink4n, that would be using aria2 for the wrong job.

It does? Well, then that seems to be more sensible.
I assume curl supports a referrers as well?
What about resume downloading?
Using aria2 due to its torrent support would be falling for [speculative generality](https://refactoring.guru/smells/speculative-generality)

What is your take on the situation @CoolnsX ?

**Comment by Dink4n** [comment]
We used to download videos using `curl` initially.
But `curl` cannot download streams. That is why we switched to `ffmpeg`.

**Comment by ura43** [comment]
But curl would work again today?

**Comment by Dink4n** [comment]
We are not downloading streams now

**Comment by ura43** [comment]
Can you do a "replace ffmpeg with curl" PR? 
But let's wait with merging either until CoolnsX can give us his take on the matter

**Comment by CoolnsX** [comment]
> > Can you investigate if migrating our curl usage to aria2 as well would be sensible?
> 
> `aria2` is an utility for downloading files
> 
> > I like a low sum of dependencies
> 
> We can use `curl` to download files. It comes with a progress bar.

We can use curl for downloading files... It's just a personal opinion.. and the features of aria2c that I like.... And I use aria2c more often than using curl for downloading files...

**Comment by CoolnsX** [comment]
> We used to download videos using `curl` initially. But `curl` cannot download streams. That is why we switched to `ffmpeg`.

I never used streams for watching anime.. i always used your old-ani-cli repo.. for watching and downloading anime.. since from the start... And it worked faster than main repo... Always.. like for e.g. month back when this master repo was using stream link.. there was some delay after selecting episode to opening mpv.. but in those times I fixed it with using download links as for watching and downloading... That's why I use aria2c for downloading because at that time gogoanime was using referer for download link at a cost of reduced speed... like 300-500 KBps.. there is used aria2c with parallel downloading.. and at those time I always got 3-5 MBps..

**Comment by Dink4n** [comment]
I used my fork of ani-cli which is a fork of old-ani-cli for watching anime.

**Comment by CoolnsX** [comment]
Yup that one.... I still use it... [Link](https://github.com/CoolnsX/repos_scripts/blob/98df9c44ecb36186dddc75642451c9db84b4f527/ani-cli)

**Comment by CoolnsX** [comment]
@Dink4n You can merge your curl one... No problem here..👍👍

**Comment by ura43** [comment]
Was interesting getting to know aria2, and without this discussion it would have taken a bit to figure out the ffmpeg dependency is really not needed anymore
