### ISSUE TITLE
Can I run it from CMD (Windows)

### ISSUE THREAD

**Issue by Hlaxfors** [pystardust/ani-cli#177]
I really just want to run it straight in cmd

**Comment by SteinGaming** [comment]
I don't think you can since it's a shell script, but you could use the windows subsystem for linux (WSL)

**Comment by Dr-S-Otter** [comment]
Yes, you can.
(I'd advise to first install windows terminal (Microsoft store) because it makes a lot of things easier)

1. Install ani-cli using git clone (same way as on Linux)
2. Install a WSL (can easily install through Microsoft store) 
3. Navigate to the ani-cli path while in the WSL and run `sudo make`
4. Exit WSL (everything after this is just in windows)
5. Install chocolatey
6. Install the dependencies of ani-cli except mpv
7. Install mpv through Sourceforge and follow these steps https://www.reddit.com/r/mpv/comments/lrprsu/how_to_open_mpv_command_line/
8. go to the ani-cli directory and copy ani-cli to ani-cli.sh
9. Change player_fn="mpv" to player_fn="mpv.exe" in ani-cli.sh

Now you can run this in cmd by going to the ani-cli directory and executing `bash ani-cli.sh`

Only downloading isn't working yet
