### ISSUE TITLE
MPV doesn't open at all (Ubuntu 18.04)

### ISSUE THREAD

**Issue by danielvelkov** [pystardust/ani-cli#216]
I tried removing the flag -f from setsid and creating the mpv conf files in the etc/mpv but there is just something missing
[debug.log](https://github.com/pystardust/ani-cli/files/7775277/debug.log)

I think the problem starts around here:
[   0.038][v][osd/libass] Using font provider fontconfig
[   0.038][v][osd/libass] Done.
[   0.038][v][ifo_dvdnav] Opening 
[   0.039][v][bdmv/bluray] Opening 
[   0.039][v][file] Opening 
[   0.039][e][file] Cannot open file '': No such file or directory
[   0.039][e][stream] Failed to open .
[   0.039][v][cplayer] Opening failed or was aborted: 
[   0.039][v][cplayer] Running hook: ytdl_hook/on_load_fail
[   0.040][v][ytdl_hook] full hook 
[   0.040][d][osc] osc_init 
[   0.040][v][cplayer] finished playback, loading failed (reason 4)
[   0.040][i][cplayer] 
[   0.040][i][cplayer] Exiting... (Errors when loading file)

**Comment by HenryQuan** [comment]
If you check this line, `Command line options: '--log-file=debug.log' '--http-header-fields=Referer: https://gogoplay1.com/embedplus?id=Mjk4NjY=&token=S5IEm8VmnrZM_bJDSFcH2A&expires=1640391794' ''`, I think the link is not parsed correctly.

**Comment by PhantomDerp** [comment]
same problem on arch

**Comment by ZN0N15** [comment]
I'm now also having this issue on Arch. Did gogoanime do something on their site to prevent links from being parsed by third party scripts?

**Comment by HenryQuan** [comment]
I think maybe that source is removed so parsing is no longer working. It happened before but not sure if it will be added back.

**Comment by AkasshShah** [comment]
Same issue on Ubuntu 20.04.3.

**Comment by MarcosHerrera97** [comment]
Hey everyone, i've been trying to debug this and it seems like the issue is with the get_links function (lines 119 - 134). The problem is most likely the regular expression used to parse the HTML of the site in order to find the video url. I don't know regular expressions though so it would be great if someone could lend a hand with that!

**Comment by HenryQuan** [comment]
@MarcosHerrera97 I think the regex is working but it couldn't find the link because it is not there.

**Comment by MarcosHerrera97** [comment]
No the link is definitely there, that is the first thing i checked. The problem is definitely the regex, most likely because they moved their videos to different pages. As a result the curl command on line 121 returns nothing,

**Comment by Malertach** [comment]
Saving the response from the curl command of line 121 `video_url=$(curl -s "$embedded_video_url" | tee response.log |` revels, that the response contains many pages worth of obfuscated code. 
Here is the start of this obfuscated code:
```javascript
<script>
    $(document).ready(function () {
        $(".videocontent #embedvideo").width($(document).width());
        $(".videocontent #embedvideo").height($(document).height());

        setTimeout(function () {
            $('.alert-type').fadeOut();
        }, 5000)

    });
</script>
<script>
    (function(_0x2c85d9,_0x37686f){var _0x137d39=_0x3ddb,_0xd7fc31=_0x27a2,_0x2a4656=_0x2c85d9();while(!![]){try{var _0x17f723=parseInt(_0xd7fc31(0x1de))/0x1+-parseInt(_0xd7fc31(0x1ed))/0x2*(-parseInt(_0x137d39(0x1e8))/0x3)+parseInt(_0xd7fc31(0x1d8))/0x4*(-parseInt(_0x137d39(0x1d7))/0x5)+parseInt(_0xd7fc31(0x1e2))/0x6*(-parseInt(_0xd7fc31(0x1ee))/0x7)+parseInt(_0x137d39(0x1d2))/0x8*(-parseInt(_0xd7fc31(0x1e3))/0x9)+parseInt(_0x137d39(0x1d4))/0xa+parseInt(_0x137d39(0x1e9))/0xb*(parseInt(_0xd7fc31(0x1dd))/0xc);if(_0x17f723===_0x37686f)break;else _0x2a4656['push'](_0x2a4656 
[...]
```
As one can see, no useful names for variables of functions.
I have no knowledge of how the response should look like, but it seems fishy. It might be a crypto miner. Or it was obfuscated to throw the parsing with the ani-cli script off. But the latter seems like a harsh action to take.

**Comment by Dev-Sam9** [comment]
@Malertach Indeed it's true. I cloned ani-cli today. How to remove it, coz I'm concerned for my privacy. It's some ransomware I'll be done for good!

**Comment by Malertach** [comment]
@Dev-Sam9 as long as you didn't open it in a web browser yuo are save.
ani-cli does not execute javascript code served by the server. It searches the html response (just a text file) for the video url and than uses a media player to play this video stream. Only a full web browser (e.g. Chrome, Firefox, Edge) executes the javascript code (because javascript is normally used to get nice, interactive webpages). 
If you didn't visit the page with a web browser all is fine. 
I have no idea, what the fishy code does but modern browsers are like a closed environment and will prevent the webpage from accessing your hard drive (unless there is a vulnerability I haven't heard of). So no encryption or extraction (leaking) of your data.
However the browser can perform the calculations necessary to mine crypto currencies ans i assume that is, what the code would do.

**Comment by MarcosHerrera97** [comment]
> @Dev-Sam9 as long as you didn't open it in a web browser you are save. ani-cli does not execute javascript code served by the server. It searches the html response (just a text file) for the video url and than uses a media player to play this video stream. Only a full web browser (e.g. Chrome, Firefox, Edge) executes the javascript code (because javascript is normally used to get nice, interactive webpages). If you didn't visit the page with a web browser all is fine. I have no idea, what the fishy code does but modern browsers are like a closed environment and will prevent the webpage from accessing your hard drive (unless there is a vulnerability I haven't heard of). So no encryption or extraction (leaking) of your data. However the browser can perform the calculations necessary to mine crypto currencies and i assume that is, what the code would do.

I am very confused. It's very obvious that the script isn't producing the expected result because the site it scrapes has altered the links to their videos. If you've followed the project or even just visited these anime sites in the past you would know that they do this frequently and its been a constant issue for this script. The script can't properly parse the HTML and find what it's looking for if the people maintaining that HTML keep moving things around. There is nothing malicious about the cli.

**Comment by PhantomDerp** [comment]
I dont think they just moved things, this looks kinda suspicious. I know companies sometimes compile javascript, bit this is in a different script tag and i see a part that isnt compiled. What does the weird part look like when it isn't obfuscated?

**Comment by MarcosHerrera97** [comment]
To be clear, I'm not speaking about whether the site itself is malicious or not. IMO that really has nothing to do with the cli tool. I'm simply explaining why the cli isn't working anymore and that is very clearly because of the site itself not the cli. Whether or not the site has implemented some malicious code is a completely different issue that should be brought up in its own issue case.

**Comment by Malertach** [comment]
> I'm not speaking about whether the site itself is malicious or not. IMO that really has nothing to do with the cli tool.
You are correct. Thank you for the clarification.
I thought if the site was compromised and is now under control of some malicious actor, the original admin of the site should be working on this issue. No changes on the cli tool would be necessary.

**Comment by sdaqo** [comment]
The first problem is that the site changed the location and the type of the video-URL (which wouldn't be hard to patch), the second is that the video-URL is only visible when the embedded video player is started (which is pretty hard to implement, at least in bash-script). You could try [my "fork"](https://github.com/sdaqo/anipy-cli)  written in python, that works.

**Comment by ura43** [comment]
> The first problem is that the site changed the location and the type of the video-URL (which wouldn't be hard to patch), the second is that the video-URL is only visible when the embedded video player is started (which is pretty hard to implement, at least in bash-script). You could try [my "fork"](https://github.com/sdaqo/anipy-cli) written in python, that works.

Could you, on a high level, tell us how you got the video url / how you started the embedded video player?
Also closing this since its once again #221
