### ISSUE TITLE
Cannot download episodes

### ISSUE THREAD

**Issue by JotaroKujo0525** [pystardust/ani-cli#219]
Hello! Suddenly I can't download episode and it always shows "Download failed <episode number>"

**Comment by Fmert24** [comment]
> Hello! Suddenly I can't download episode and it always shows "Download failed "

Downloda fails 

Getting data for episode 11
Current video quality is not available (defaulting to highest quality)
Downloading episode 11 ...

Download failed episode: 011
And changing quality has no effect

**Comment by JotaroKujo0525** [comment]
Yep, that's what happening to me

**Comment by TripleK2004** [comment]
Yep, same here : (

**Comment by SotchNam** [comment]
Same, hope you can fix it soon

**Comment by Abhiwa6** [comment]
Not going to fixed soon

**Comment by Abhiwa6** [comment]
there's nothing wrong with the scraper tool, it seems like the base server has turned on an extra level of security, that's why the tool is unable to retrieve data. Changing the base URL also didn't help. So it's better to use the website gogoanime.cm/wiki for some time. It's like you've to choose between GUI and Anime XD

**Comment by ura43** [comment]
Related to #221, discussion continues there
