### ISSUE TITLE
Program "vlc" not found(Windows 10)

### ISSUE THREAD

**Issue by Anarchyserver** [pystardust/ani-cli#222]
im on windows 10 and am receiving this error even though vlc media player is installed in the recommended directory. im running git as admin aswell
![windows10vlcnotfound](https://user-images.githubusercontent.com/84468874/147571327-97457d47-5349-4176-a06a-0b7ad32cc08b.PNG)

**Comment by Jasiri-w** [comment]
**Solution**: Add VLC to PATH environment variable

### Explanation
ani-cli requires the VLC.exe executable program file to be available from anywhere on the command line ( i.e. if you type in cmd or npm from any directory from the command line the program will run ).

### Instructions
Therefore you need to add the line 
**_"C:\Program Files\VideoLAN\VLC"_**
to the PATH. _( That file path is the default install location for VLC. In case yours is different, to find where yours is either right click a VLC shortcut and go to properties and look for the value labelled 'Start In' as your folder location or search for vlc.exe through explorer)_

**Method 1**
The easiest way to add to PATH is through cmd. (however it is a bit dangerous as you could erase all of your variables by mistake) 

1. First type 'path' to see all the current path variables. 
2. Then type `' set path = %path%;C:\Program Files\VideoLAN\VLC '`
_**Note:** do not forget the '%%' around path as that signifies the variable, otherwise it will place a raw string. Its like typing x=x+1. The ';' between %path% and the 'C:' is also imperative, do not forget it as it signifies a new path string._

**Method 2**
You can add a new folder to path by searching for "Environment Variables" from the taskbar search box. An option called "edit environment variables" should appear. Select it and you should see a settings window appear. Select the "Environment variables" button at the bottom of the window. From the window that appears there are 2 distinct boxes, the lower one named "System variables" will have a row for "path": double click it. In this new window select "new" and copy paste the folder location _"C:\Program Files\VideoLAN\VLC"_

**Note:**_You want the encapsulating folder path, not the ".exe"'s full file path_
**Note:**_If you are unable to edit the variables in the bottom box, edit, in the same way, the path variable in the top box, but it will not be available to every user on the computer_

Done!
Enjoy your anime and remember..._its ecchi, not hentai ;)_

If you need another explanation [here it is](https://stackoverflow.com/a/9546345)

**Comment by Anarchyserver** [comment]
> 

either im doing it wrong or its not working, i tried both methods but still nothing

**Comment by TheGlockMisc** [comment]
> > 
> 
> either im doing it wrong or its not working, i tried both methods but still nothing

Double check it.. Probably your VLC program installed in "C:/Program Files (x86)/VideoLAN/VLC
