### ISSUE TITLE
Windows10, Vlc error: "Codec cannot be identified" AND "Input data can't be read"

### ISSUE THREAD

**Issue by Tuttori** [pystardust/ani-cli#354]
Everything works just fine untill I select an episode to play.

Vlc launches but then shortly after I get flooded with: Unidentified codec: "VLC could not identify the audio or video codec" errors

And in the middle of these "Codec errors" there's also this ( appears only once ):

Your input can't be opened:
VLC is unable to open the MRL 'file:///C:/Program%20Files/Git/etc/pki/ca-trust/extracted/pem/objsign-ca-bundle.pem'. Check the log for details.

Running it on Windows 10 Pro, downloaded latest versions of ani-cli and vlc
It gave the same errors for various shows ( tried: Jujutsu Kaisen, AoT, Youjo Senki )

**Comment by ccireedui** [comment]
Having same problem.

**Comment by ura43** [comment]
I assume this is related to our url decryption.
Do you have openssl installed?

**Comment by ura43** [comment]
It says "Check the log for details"
Mind sharing those?

**Comment by Tuttori** [comment]
> It says "Check the log for details" Mind sharing those?

It doesn't seem like I have openssl ( I only see openssh in Paths )
And I can't find where the log is :/

**Comment by ccireedui** [comment]
These are the errors I'm getting and the log file.

![image](https://user-images.githubusercontent.com/51305170/150382418-102792e3-32a7-48a4-8a2b-56c2b0df785c.png)
[log.txt](https://github.com/pystardust/ani-cli/files/7906993/log.txt)

**Comment by RaynardGerraldo** [comment]
> These are the errors I'm getting and the log file.
> 
> ![image](https://user-images.githubusercontent.com/51305170/150382418-102792e3-32a7-48a4-8a2b-56c2b0df785c.png) [log.txt](https://github.com/pystardust/ani-cli/files/7906993/log.txt)

is that git bash? you dont have jq installed there, the links wouldnt even be parsed

**Comment by RaynardGerraldo** [comment]
@Tuttori @ccireedui try running this

`curl -L -o /c/windows/system32/jq.exe https://github.com/stedolan/jq/releases/latest/download/jq-win64.exe`

then re-run ani-cli

**Comment by Memotets** [comment]
After facing this issue today, a have to say that on windows sadly the curl .exe sent didn't really help at all,  but because i only had detected this issue after some cache clears or changes on your web browser that you should work out for future upgrades...  

the dumb solution that i have found for the current version was easily to reinstall ani-cli, and before first run, erase the folder %appdata%/vlc to open vlc as "first run"

**Comment by RaynardGerraldo** [comment]
> After facing this issue today, a have to say that on windows sadly the curl .exe sent didn't really help at all, but because i only had detected this issue after some cache clears or changes on your web browser that you should work out for future upgrades...
> 
> the dumb solution that i have found for the current version was easily to reinstall ani-cli, and before first run, erase the folder %appdata%/vlc to open vlc as "first run"
> 
> edit: Try this solution and let us know how it goes

can you elaborate more on what this fixes? because this issue was regarding jq not installed as stated in the log file and the image sent

**Comment by Memotets** [comment]
Allright, let get deep into it....

### **Starting with what did i do that did not directly work** 

-   Downloading jq on gitbash as you recommend. _even after installation somehow the problem persist._
-   Upgrate OpenSSL. [check this repo](https://github.com/openssl/openssl/blob/master/INSTALL.md)
-   Change the default web browser of your computer. 

this changes were made before those who actually did something, but there are important considerations in order to the sistem to work properly.

### **What did i do in order to fix this?**

1. Open git bash as admin and go to your ani-cli directory: `cd [PATH-TO]/[ANI-CLI]/ani-cli`.
2. Run `./uninstall` which is the first step in order to reinstall ani-cli.
3. After finish the uninstall, restart your system in order to do the changes.
4. On the new start you have 2 options in order to install ani-cli
4.1.On gitbash, as admin, go tu your ani-cli directory and instaling over there
4.2.Erase ani-cli directory and install it as the README.md says from _Run the following commands_ point
```
### 4.1 commad instructions ###
cd [PATH-TO]/[ANI-CLI]/ani-cli
 ./install
```
 ```
### 4.2 commad instructions, as admin ###
git clone -b windows-vlc https://github.com/pystardust/ani-cli.git
cd ani-cli
chmod +x ani-cli-win
./install
```

> _both ways should work fine, but i personaly did 4.2 in order to be sure nothing weird happend_

after intallation, my ani-cli didn't have problems at all
