### ISSUE TITLE
Not working with mpv flatpak

### ISSUE THREAD

**Issue by BRINGit34** [pystardust/ani-cli#366]
I have mpv installed through flatpack so I really don't know why it says it isn't installed. I am on fedora 35. Any help would be appreciated

**Comment by ura43** [comment]
This is expected behaviour with flatpaks.
You shouldn't be able to lauch mpv by simply typing mpv in the Terminal.
It will need to be launched through `flatpak run io.mpv.Mpv`.
The most simple fix would be to install it through your native package manager.
There is a less recommended workaround if that is not an option for you

**Comment by BRINGit34** [comment]
Yeah the native package works. Thank you. I just assumed the flatpak would work the same. My apologies
