### ISSUE TITLE
[Feature-Request] I wanna know if ani-cli can use Spanish subtitles or something like that.

### ISSUE THREAD

**Issue by dustxyz** [pystardust/ani-cli#4]
And yeah i don't have a fluent english, i need atleast something in spanish lol

**Comment by Ytr00m** [comment]
Its a cool idea, can you add a way to choose between the two or more subtitles?

I haven't a fluent english as well, I speak Portuguese.

**Comment by kaykay38** [comment]
@dustxyz This capability is dependent upon the video source from gogoanime. When the video is playing, you can press `j` to cycle through the subtitles. If there is no Spanish subtitle, then it will have to be downloaded from another website.

@Ytr00m As for multiple subtitles, it will be difficult because the video source is streamed and you cannot select more than one subtitle simultaneously from an online video. I am not sure if it can work when it is downloaded. This capability does exist in mpv, but it has limits. Two subtitles must be specified in the mpv launch command. Multiple subtitles cannot be selected while playing the video.

**Comment by dustxyz** [comment]
> @dustxyz This capability is dependent upon the video source from gogoanime. When the video is playing, you can press `j` to cycle through the subtitles. If there is no Spanish subtitle, then it will have to be downloaded from another website.
> 
> @Ytr00m As for multiple subtitles, it will be difficult because the video source is streamed and you cannot select more than one subtitle simultaneously from an online video. I am not sure if it can work when it is downloaded. This capability does exist in mpv, but it has limits. Two subtitles must be specified in the mpv launch command. Multiple subtitles cannot be selected while playing the video.

Okay thanks

**Comment by Ytr00m** [comment]
> @dustxyz This capability is dependent upon the video source from gogoanime. When the video is playing, you can press `j` to cycle through the subtitles. If there is no Spanish subtitle, then it will have to be downloaded from another website.
> 
> @Ytr00m As for multiple subtitles, it will be difficult because the video source is streamed and you cannot select more than one subtitle simultaneously from an online video. I am not sure if it can work when it is downloaded. This capability does exist in mpv, but it has limits. Two subtitles must be specified in the mpv launch command. Multiple subtitles cannot be selected while playing the video.

First thank you for the feedback, I mean choose before playing the video, I am leaning programming and maybe I can contribute in a way to choose the server that it collect the video from.

Sorry for the bad English :(
