### ISSUE TITLE
Why did ani-cli switch from gogoanime to gogoplay?

### ISSUE THREAD

**Issue by hackedXD** [pystardust/ani-cli#652]
Sorry idk much bout ani-cli in general, but why switch. Search is worse, constant key changes. What are the benefits to gogoplay?

**Comment by CoolnsX** [comment]
Gogoanime is the frontend of gogoplay.. so we were like frontend of a frontend of gogoplay.. so the solution is to cut the middle man... only search is worst (but we already implemented a workaround, which inturn makes the script slow at beginning.. hack : if u search the respective anime in its Japanese name.. it will search it's faster.. like shingeki no kyojin instead of attack on titans) rest url parsing and other script's features are good..

**Comment by CoolnsX** [comment]
and if we switch back to gogoanime the result would be same..

**Comment by hackedXD** [comment]
Oh ok. Thx. :)
