### ISSUE TITLE
options doesnt show

### ISSUE THREAD

**Issue by nightser727** [pystardust/ani-cli#701]
1. Run 'ani-cli -q best -c

**Expected behavior**
should show the options
it works when searching for a new anime

https://user-images.githubusercontent.com/84193446/166121132-dd848262-99e4-40e8-97b4-0a77e8d20923.mp4

**Comment by iamchokerman** [comment]
what do you mean by "should show the options"?

**Comment by Derisis13** [comment]
This is the `one-hist` feature: if you have a single history entry, the auto-play is automatically turned on.
This is by design, even though I don't like it.
A quick fix can be that you add another entry to your history.
I would consider changing auto-play to off by default (even in a `one-hist` case) and have it toggled by -a. This might even save us some lines without losing functionality and clear up some confusing behaviour.

**Comment by Derisis13** [comment]
I want @port19x 's opinion on this though

**Comment by iamchokerman** [comment]
that was done on purpose, let me find the original reference

**Comment by iamchokerman** [comment]
#577 and  #555

**Comment by port19x** [comment]
> I want @port19x 's opinion on this though

Please keep -c automatically selecting the only entry when applicable
