### ISSUE TITLE
Add addtitional meta-data for the downloaded videos

### ISSUE THREAD

**Issue by KitsuneRanger** [pystardust/ani-cli#732]
I think it's a pretty good idea to feature meta-data to the downloaded videos.
like example: I want to tidy up my animes on iTunes (yes, I download on Linux and copy to my Windows and to my iTunes to copy to my phone....). I don't ask for highly detailed metadata. It's enough if it contains the title and tv series name. So If I open the properties of the file I can see few metadata about it.

**Example to the file**
File name: jojo-no-kimyou-na-bouken-part-6-stone-ocean-dub-episode--001.mp4
Title: Stone Ocean
Tv Series: jojo no kimyou na bouken part 6 stone ocean

I know it's probably hard to do this, If you have some spare time...

**Comment by KitsuneRanger** [comment]
Oh snap, I just realised I need to format this, like you did....
Sorry! 😰😰😰

**Comment by Derisis13** [comment]
This is outside of the scope of the project. Not only because the storage of these metadata is not on the scraped sites (no episode titles and no English series name), but also editing the metadata into the files would require an external tool or a lot of code, both of which we're cautious to add.
I think you're better off with an external tool or relying on torrents which come with superior metadata.
