### ISSUE TITLE
/usr/local/bin/ani-cli: 470: .: Can't open /usr/local/bin/players/player_mpv

### ISSUE THREAD

**Issue by susukin0** [pystardust/ani-cli#751]
Version: []
OS: [Linux Mint 20.3]
Shell: [dash]
Anime:[]

any kind of output i get from ani-cli is:
/usr/local/bin/ani-cli: 470: .: Can't open /usr/local/bin/players/player_mpv

**Steps To Reproduce**
$ ani-cli
/usr/local/bin/ani-cli: 470: .: Can't open /usr/local/bin/players/player_mpv
*
*Expected behavior**
search anime:

**Comment by DaBigBlob** [comment]
after the update to V3 the players are in the `players` directory separate from the main ani-cli script.
but when you install according to the installation instructions, the `players` directory doesnt get downloaded.

PROBLEM: installation instructions outdated

NOTE: this is not a bug

well, why not just put all the player code into the main script i.e. ani-cli?
because as we add support for more players, we shouldn't have to fiddle with the main script. thats it.


TEMPORARY MITIGATION: clone the whole repo using `git clone "git@github.com:pystardust/ani-cli.git"` and things should work fine from within the ani-cli directory.

CAVEAT FOR TEMPORARY SOLUTION: you cannot access ani-cli from any directory as its not in your path

**Comment by justchokingaround** [comment]
Updating to version 3:

Create the directory for the players: sudo mkdir "$(dirname "$(which ani-cli)")/players"
Then update ani-cli again, to recieve player and UI scripts: sudo ani-cli -U
For linux, and mac it should be the same process, for windows you need to run gitbash as administrtor then use the same commands, without sudo

**Comment by justchokingaround** [comment]
will add this to readme soon™️

**Comment by DaBigBlob** [comment]
@susukin0 
anyone on Linux and MacOS can use this:
https://github.com/DaBigBlob/ani-cli/tree/fixed

do not use the main branch on my repo; use the fixed brance;
the main branch is for the pull request: https://github.com/pystardust/ani-cli/pull/753
