### ISSUE TITLE
Some anime are not available in search result, although they are in animixplay.

### ISSUE THREAD

**Issue by Upsurge-11** [pystardust/ani-cli#778]
Version: 3.1.0
OS: Arch Linux
Shell: bash
Anime: monster

The anime is not showing after searching in terminal, although it is present in animixplay. The thing is, it doesn't show in animixplay until u search and press enter, it won't suggest the anime while u search.

1. Run ani-cli
2. search monster

the anime should be visible.
![image](https://user-images.githubusercontent.com/57493726/174491093-4a77a4d6-923d-46e3-92c6-1177605178cd.png)
![image](https://user-images.githubusercontent.com/57493726/174491110-c2f01b84-362d-46f4-857b-f44d9f22b115.png)

**Comment by simontaglev** [comment]
Indeed!
Just now tried to watch the old Berserk.
It shows only the modern seasons and the dub, no old sub which is still available on animixplay.
Uninstalled and installed again, no change; it still doesn't show up.

**Comment by jacksprayson** [comment]
Version: 3.0 (latest)
OS: Mac
Shell: bash
No idea why it's working that way, but temporary fix that worked for me was to:
1. Try different names for the series ie. "Kimetsu no Yaiba" vs. "Demon Slayer"
2. Use quotation marks around searched series' name
3. Try searching with both command-line arguments and with the built-in query request

No guarantee it works all the time.
Hopefully someone figures out what's wrong, because I have no clue.

**Comment by Derisis13** [comment]
Solution in the works (#774)
