### ISSUE TITLE
When I searched for a specific anime, the result returns to 'video URL not found'

### ISSUE THREAD

**Issue by bryz27** [pystardust/ani-cli#884]
**Metadata (please complete the following information)**
Version: 3.3
OS: Windows 10
Shell: git bash
Anime: Ore Dake Haireru Kakushi Dungeon

**Describe the bug**
After I enter the name of the anime and selected episode, it outputs hex errors and then results to 'video URL not found'

**Steps To Reproduce**

1. Open git bash normally
2. Run ani-cli
3. Input 'ore dake'
4. choose 4
5. choose 7 (episode)

**Expected behavior**
![image](https://user-images.githubusercontent.com/41132951/188872046-a2edc0a3-f4af-49fd-9bf3-754e3a929849.png)

**Comment by UmiKami** [comment]
Same thing happening here.
**Metadata (please complete the following information)**
Version: 3.3.4
OS: MacOS Monterrey 12.5.1
Shell: zsh
Anime: Isekai Meikyuu 

**Describe the bug**
After I enter the name of the anime and selected episode, it outputs hex errors and then results to 'video URL not found'

**Steps To Reproduce**

Open git bash normally
Run ani-cli
Input 'ore dake'
choose 4
choose 7 (episode)
![image](https://user-images.githubusercontent.com/60261375/189020347-c3cf135a-efdb-4adb-bf0c-8f4d6bd38151.png)

Note: reinstalling ani-cli does not solve the issue.

**Comment by port19x** [comment]
Seems like our cryptography / url extraction broke due to a provider-side update.
I'll prepare release notes for a v3.4 point relase once the fix hits master.
I can't provide further debugging info as I'm behind a corporate firewall.
Note to the other maintainers: don't bother with any debloating efforts we wanted to do now that our spec is ready, those can come as v3.4.x

**Comment by port19x** [comment]
Thorough release notes are prepared :heavy_check_mark:
