### ISSUE TITLE
No search results found??

### ISSUE THREAD

**Issue by MaccaAlbarn** [pystardust/ani-cli#897]
**Metadata**
Version: [3.4.0, installed trough the AUR]
OS: [Artix Linux with linux-5.19.6.artix1-1 kernel]
Shell: [zsh]
Anime: [Any]

**Describe the bug**
Every time i try to search for an anime, like devil survivor, shows the message "No search results found"

**Steps To Reproduce**

1. Run `ani-cli`
2. Search for any anime, (Example : those in the screenshot)

**Expected behavior**
Anime list should show

**Screenshots**
![Screenshot from 2022-09-13 21-18-07](https://user-images.githubusercontent.com/104636370/190052974-ad9de4a4-f520-4c4d-b904-8366ebadc02d.png)

**Additional context**
I did a clean install of artix recently, i installed every program that i use, including of course, ani-cli, i tried to run it yesterday and it showed the previous message, same thing today

**Comment by CaffeineB34r** [comment]
On my Windows machine I did some digging and found out that curl was not working cause it required TLS certificates, so try to manual run `curl "https://www.google.com/"`, if it suggests you to check this "https://curl.se/docs/sslcerts.html" out it's cause you can either ignore the issue running ` sed -i 's/curl\ /curl\ -k\ /g' ani-cli` or try to solve it by installing certificates. Maybe your issue is different(bcs OS), but I can only reproduce it on Windows

**Comment by justchokingaround** [comment]
also try checking if animixplay works in the browser
