### ISSUE TITLE
Connection problems to search and update

### ISSUE THREAD

**Issue by SttavoS** [pystardust/ani-cli#921]
Version: 3.4
OS: Windows 10
Shell: Git Bash
Anime: Lupin

**Describe the bug**
Prompts print "No search results found"

**Steps To Reproduce**

1. Run `ani-cli`
2. Write "lupin"

**Expected behavior**
Search and list the options.

**Screenshots**
![image](https://user-images.githubusercontent.com/59072856/198897442-d1b171d5-7586-4b07-9146-2942170122ed.png)

**Additional context**
This is happening to a friend of mine, it's working perfectly for me. I suggested for him to update the CLI with `ani-cli -U`, but it didn't work because of connection issues.
![image](https://user-images.githubusercontent.com/59072856/198897919-6e5fa303-9c71-49f4-a9ca-f09027b30481.png)

**Comment by Derisis13** [comment]
Please check if your friend can reach animixplay at all, it could beblocked by an ISP/government

**Comment by SttavoS** [comment]
> Please check if your friend can reach animixplay at all, it could beblocked by an ISP/government

@Derisis13  He has access and is able to access the site normally, but the CLI doesn't find anything

**Comment by Derisis13** [comment]
The issue is most likely somewhere in windows or in git bash: it appears that no program in git bash can reach the internet. 
I couldn't find anything useful at the moment, and I don't have the expertise to troubleshoot git bash, so I can't really help you with this one. Re-installing git bash then installing ani-cli again might bring it to life, but all configuration (including the histfile) will be lost unless backed up.

**Comment by JellyJones** [comment]
![image](https://user-images.githubusercontent.com/8754625/203180569-57cc13a9-bb46-47f2-bf47-cd50742821f7.png)
I too seem to have this issue on arch linux unless I'm in a root shell.

**Comment by port19x** [comment]
firewall issue maybe?

**Comment by port19x** [comment]
Please reopen if you want further support
