### ISSUE TITLE
Episodes is broken.

### ISSUE THREAD

**Issue by Denilson-Semedo** [pystardust/ani-cli#927]
Version: 2.0.0 
OS: [e.g. Windows 10 / Linux Mint 20.3]
Shell: bash
Anime: boruto but it's hapenning in others animes to like Mob Psycho for example . . .

**Describe the bug**
Episodes is broken.
It says something about Episode doesn't exist!! and Video URL not found

**Steps To Reproduce**
1. Run `ani-cli`
4. Search Boruto
3. Choose option (1)

**Expected behavior**
episodes should open

**Comment by justchokingaround** [comment]
Please first check that [animixplay.to ](animixplay.to) works for you in the browser. If it doesn't, then you have to use a vpn or a proxy like 1.1.1.1

**Comment by LiamPalmqvist** [comment]
Happening to me, too. 
![Screenshot 2022-11-14 at 19 31 15](https://user-images.githubusercontent.com/38404738/201748899-c0408296-785e-4e76-9371-d14ad942113d.png)

**Comment by Derisis13** [comment]
Please fill in the correct version + OS + shell informations! We can't do much debugging if we have to guess the version.
2.0.0 is a severely outdated version and will not work. Update to the latest version by running `sudo ani-cli -U` on linux & mac, or `ani-cli -U` in git bash ran as administartor on windows; and see if it resolves anything.

**Comment by Denilson-Semedo** [comment]
> Please first check that [animixplay.to ](animixplay.to) works for you in the browser. If it doesn't, then you have to use a vpn or a proxy like 1.1.1.1

yeah animixplay.to its working fine

**Comment by Skepller** [comment]
Same problem trying to watch _Bleach: Sennen Kessen-hen_ Episode 9, it prints "Video URL not found".

The episode is already available at [animixplay](https://animixplay.to/v1/bleach-sennen-kessen-hen/ep9) and the script is already up-to-date (Version: 3.4.6).

Maybe something related to newly released episodes? Since this one came out today.

Specs:
OS: Pop!_OS 22.04 LTS x86_64 
Kernel: 6.0.6-76060006-generic 
Shell: bash 5.1.16 
CPU: Intel i7-10750H
GPU: NVIDIA GeForce RTX 2060 Mobile 
Memory: 16GB

**Comment by Skepller** [comment]
Yes, plays fine on browser, "Video URL not found" on ani-cli.

**Comment by port19x** [comment]
> _Bleach: Sennen Kessen-hen_

Can't reproduce. Latest version plays both `bleach sennen kessen hen Ep 9`, `boruto the movie` and `mob psycho 100`

Seems to be an issue outside of our control
