### ISSUE TITLE
episodes ending randomly

### ISSUE THREAD

**Issue by kono7** [pystardust/ani-cli#941]
**Metadata (please complete the following information)**
Version: 3.4
OS: Arch Linux
Shell: bash
Anime: One Piece

**Describe the bug**
When watching an episode, sometimes it will randomly end and play the next episode.

**Steps To Reproduce**

1. Run `ani-cli one piece`
2. Choose 1
3. Choose any episode
4. Watch until it randomly ends

**Expected behavior**
1. Run `ani-cli one piece`
2. Choose 1
3. Choose any episode
4. Watch until it ends and the next episode plays

**Comment by Derisis13** [comment]
I have experienced the same thing, and I have yet to find what causes it. My solution was to just replay the episode, although if you are using a range selection, it's not possible. 
Since it is most likely a provider thing, you can try defaulting to a different one with `-r2` or `-r3`. And I'll try to look into if it's possible to auto-restart failed episodes

**Comment by port19x** [comment]
Also closing because this is likely going to be solved in v4 on accident.
As always you're welcome to reopen once that update rolls out if the issue persists
