### ISSUE TITLE
Can't watch episode 1 of Attack on Titan Season 4 part 2

### ISSUE THREAD

**Issue by olddesklamp** [pystardust/ani-cli#943]
**Metadata**
Version: 3.4
OS: Pop!_OS 22.04
Shell: fish, bash
Anime: Attack on Titan

**The bug**
`Video URL not found` error when attempting to watch the second part of Attack on Titan's final season.

**Steps To Reproduce**

1. Run `ani-cli`
2. Choose 19 (shingeki no kyojin the final season part 2)
3. Choose 1

**Expected behavior**
Should be able to watch the episode as normal

**Additional context**
I've tried downloading as well, with the same results. The rest of the season streams and downloads just fine, this issue only exists with the first episode.

**Comment by Derisis13** [comment]
This is a rare occurrence of wrongly numbered episodes on animixplay: if you look close, the upper limit of episodes is 13, but this series only has 12. What happens is all eps are marked one later then they are: the 1st becomes the 2nd, the 2nd the 3rd and thus the 1st is invalid. So you should always check episode 2 to see if it's not really episode one (it is in this case).
It's not unique to attack on titan 4 part 2, for example tensura has the same issue. Since all episodes are still playable, we haven't bothered to fix this particular error.
