### ISSUE TITLE
hex string is too short,  padding with zero bytes to length Video URL not found

### ISSUE THREAD

**Issue by gunnnu** [pystardust/ani-cli#945]
**Metadata (please complete the following information)**
Version: 3.4 (latest)
OS: WSL in Windows 11
Shell: zsh
Anime: Dragon Ball Super (Dub)

**Describe the bug**
I am getting the following Error  : 
```
Fetching Gogoanime Direct link..hex string is too short, padding with zero bytes to length
hex string is too short, padding with zero bytes to length
bad decrypt
139822611084608:error:0606506D:digital envelope routines:EVP_DecryptFinal_ex:wrong final block length:../crypto/evp/evp_enc.c:599:
hex string is too short, padding with zero bytes to length
hex string is too short, padding with zero bytes to length
Video URL not found
```

**Steps To Reproduce**

1. Run `ani-cli  Dragon Ball Super dub`
2. Choose 1 (dragon ball super dub)
3. Choose episode 74/75/76 (any episode)

**Expected behavior**
Should start streaming episode

<img width="581" alt="image" src="https://user-images.githubusercontent.com/44329075/208762696-4a3bd644-2814-4011-a874-4d89c4634d4e.png">

**Additional context**

I installed from source cloning the git repo and copying to /usr/local/bin as other ways do not work properly.
I tried reinstalling the same way again

I am facing this issue since my system hibernated. I was watching ep 74 and then in middle my system hibernated when I started my system again it was not working for the particular Anime I was watching (`Dragon Ball Super`) others are working fine.

My Guess: 
* probably some cache issue , I tried but could not find if this tool stores cache anywhere.

**Comment by Derisis13** [comment]
Couldn't reproduce on Pop!_OS, might be a WSL thing. I recommend you to install it trough scoop, from git bash. If something doesn't work there, you can check out our discord server, since there were quite a few discussions about windows there.
As for cached files we have: `ani-url` (storing the url associated with animixplay, updates when animixplay chages it) and `ani-hsts` which stores the history (for `-c`). They are at `${XDG_CACHE_HOME}` if it exists or at `~/.cache` if not. And I don't really think either of them can corrupt in such a way ani-cli broke like this. You can remove them if you feel like, they'll get generated again.
One other source of issue can be that [animixplay](https://animixplay.to/) is blocked somewhere. Could be an ISP, could be your LAN. You should try to see if it's available in a browser.

**Comment by gunnnu** [comment]
Hey @Derisis13 , Thanks for your comment. 
Seemed like issue with network itself the URL probably was blocked, since I connected using VPN and it is working fine now.
Although a weird thing is that before using vpn it was pulling form gogoanime as you can see in the screengrab as well but when I tried to watch it on gogo anime on browser it is working fine. 

Also initially I tried installing it via scoop but for some reason it can not find mpv installed , which i already installed before ani-cli from scoop itself. that is why I used installation from source.

Anyways, Thanks for the help.
