### ISSUE TITLE
Cant detect mpv

### ISSUE THREAD

**Issue by NaufalF22** [pystardust/ani-cli#959]
![gambar](https://user-images.githubusercontent.com/63091744/209796525-b8a8501a-fda5-4c72-a90b-d2fb873f442a.png)
I've already install mpv from scoop but ani-cli cant detect

**Comment by teymurov27** [comment]
Look for where ani-cli looks for mpv. Have you checked the location ?

**Comment by NaufalF22** [comment]
> Look for where ani-cli looks for mpv. Have you checked the location ?

How to check that?

**Comment by justchokingaround** [comment]
you need to check whether or not mpv is in path, so basically check if running the `mpv` command returns something

**Comment by NaufalF22** [comment]
> you need to check whether or not mpv is in path, so basically check if running the `mpv` command returns something

![gambar](https://user-images.githubusercontent.com/63091744/209805016-675eb45e-8ba1-4414-81cb-104ae98a3f40.png)
Its return something

**Comment by ExoForceGen1** [comment]
I am experiencing a similar problem. It continues to tell me that mpv cannot be found even though I installed it using scoop and it runs fine.
<img width="954" alt="image" src="https://user-images.githubusercontent.com/121591576/209896234-e4e3784a-998c-4b9c-a34c-88b19c68ee8c.png">

**Comment by Vacbo** [comment]
I am having the same problem and mpv is in the $PATH, so I don't know what is the cause of the error.

**Comment by Vacbo** [comment]
> > Look for where ani-cli looks for mpv. Have you checked the location ?
> 
> How to check that?

Search "edit the system environment variables" in windows search bar, should open something like this:
![image](https://user-images.githubusercontent.com/53411412/209912573-f3070d9a-068b-4cac-a0bf-09b87f0cdcea.png)
Then click environment variables and search for the variable called "Path" and click on it. If the folder location for mpv is there, it should be all right. However I am having the same problem and mpv was added in $PATH by scoop.

**Comment by Vacbo** [comment]
I guess this error could be fixed when ani-cli 4.0 launches. The devs seem to be working on it recently.

**Comment by uzuto** [comment]
It was working correctly before commit 9dcddb994d0f0fca56313b670b7b86ffacb4d060

**Comment by PutPasswordHere** [comment]
Friend had a similar issue, installing mpv through scoop and having the same environment variables as me (worked fine through his Linux, but Windows messed up). He could launch mpv through gitbash, but ani-cli wouldn't detect it. Think he said he made a symbolic link to MPV, and that somehow picked it up.

**Comment by KeyBrute** [comment]
the ani-cli support member told me to use windows store version of mpv... it actually worked lmao

**Comment by Justaus3r** [comment]
This happened a while back to [adl](https://github.com/RaitaroH/adl) and is due to git bash not being able to properly adopt PATH or smth(forgotten as this was year ago). something similiar to [here](https://github.com/RaitaroH/adl/issues/27#issuecomment-911896984) (tho much simpler) can be done for detecting players on windows. i can take a look after v4 is complete or the logic can be implemented by the core devs.

**Comment by stl3** [comment]
I've had issues with scoop installed mpv and even portable mpv a along, long time ago even with path added to environment on win10 to work with ani-cli, so I've made it a practice to edit ani-cli whenever it's been updated to use mpv.com instead of mpv which made it work for me. I just stuck with using .com instead of the .exe because launching .com lets me see console with my mpv scripts (in general, not visible with ani-cli though). Doing this enables me to use ani-cli with mpv in powershell or gitbash no problems.

**Comment by cdulloa** [comment]
Downloading mpv from the windows store seems to work.

**Comment by alpha-hexor** [comment]
in git bash do this ``alias mpv="mpv.exe"`` that worked for me

**Comment by DanSM-5** [comment]
Mpv from scoop is working fine on my pc but I just recently tried in a laptop and gitbash was unable to find mpv. Weirdest thing was that both were the same version installed from scoop (v0.35.0).

After a couple of digging I found the reason. The manifest for mpv was updated to use the path to mpv (mpv.com) instead of creating a shim file https://github.com/ScoopInstaller/Extras/commit/8f71579d638c49e7d1312069cffeeca53774578a

I don't know how to create a shim myself but I tried by installing mpv using the previos manifest (one commit previos the path change)

```
scoop install https://raw.githubusercontent.com/ScoopInstaller/Extras/a7f6726ad34dd8abca908c1882d1e150f0662477/bucket/mpv.json
```
and that did the trick to make it work on gitbash.

**Comment by candrapersada** [comment]
the mpv file and ani-cli must be placed in the same folder but if it's in the separate folder it doesn't work even using environment variables path.

**Comment by candrapersada** [comment]
try deleting the mpv folder from scoop and try again it should work
![mpv](https://user-images.githubusercontent.com/36833664/211440998-09ce4c6c-c8af-4b02-9612-13dca1f9d2e4.PNG)

**Comment by streepje8** [comment]
If you have this issue on windows. You can try opening the ani-cli script (C:\Program Files\Git\usr\bin\ani-cli) in a program like notepad++. Then replace all "mpv" with "mpv.exe"

I'm not sure why since I'm not a hero with git bash, but that fixed it for me. Messing around with the path and aliases all did nothing but that replace made it work for me again.

I would open a pull request for it. But I'm not sure if this only affects a small portion of the windows userbase. And it would also break the script in linux so it would never get accepted. But I hope something can be done with this info ^_^

**Comment by GauravBariha** [comment]
I had the same problem with mpv not being found so i uninstalled it using scoop then i ran powershell as administrator then re-installed the mpv through scoop , then i got the message " xyz - path" has been added to the system variables  , then i tried to run ani-cli and everything is working fine.

**Comment by GauravBariha** [comment]
I had the same problem with mpv not being found so i uninstalled it using scoop then i ran powershell as administrator then re-installed the mpv through scoop , then i got the message " xyz - path" has been added to the system variables , then i tried to run ani-cli , then option showed up to enter name of anime , after i wrote the name and pressed enter i got the error - "curl: option --cipher is unknow" so i uninstalled ani-cli from scoop , updated the scoop then re-installed ani-cli & everything was working fine.

**Comment by GuiReboucas** [comment]
> try deleting the mpv folder and try again it should work ![mpv](https://user-images.githubusercontent.com/36833664/211441474-d0532d3f-cea2-46a8-bf9a-3b66e7fdea47.PNG)

Why the hell this worked?

**Comment by x8laye4r** [comment]
> Mpv from scoop is working fine on my pc but I just recently tried in a laptop and gitbash was unable to find mpv. Weirdest thing was that both were the same version installed from scoop (v0.35.0).
> 
> After a couple of digging I found the reason. The manifest for mpv was updated to use the path to mpv (mpv.com) instead of creating a shim file [ScoopInstaller/Extras@8f71579](https://github.com/ScoopInstaller/Extras/commit/8f71579d638c49e7d1312069cffeeca53774578a)
> 
> I don't know how to create a shim myself but I tried by installing mpv using the previos manifest (one commit previos the path change)
> 
> ```
> scoop install https://raw.githubusercontent.com/ScoopInstaller/Extras/a7f6726ad34dd8abca908c1882d1e150f0662477/bucket/mpv.json
> ```
> 
> and that did the trick to make it work on gitbash.

Thanks this worked for me

**Comment by DanSM-5** [comment]
@x8laye4r If you want to use an updated mpv, you can create the shim manually like this

```bash
scoop shim add mpv C:\Users\[user]\scoop\apps\mpv\current\mpv.com
```

**Comment by x8laye4r** [comment]
> @x8laye4r If you want to use an updated mpv, you can create the shim manually like this
> 
> ```bash
> scoop shim add mpv C:\Users\[user]\scoop\apps\mpv\current\mpv.com
> ```

Okay thanks. I will try it later then

**Comment by Lauloque** [comment]
I was [pointed out](https://github.com/pystardust/ani-cli/issues/1529#issuecomment-3239422081) that I used `%GIT_INSTALL_ROOT%\usr\bin\bash.exe` instead of `%GIT_INSTALL_ROOT%\bin\bash.exe`, that fixed it even with the mpv folder.

Lesson of the day: read carefuly

**Comment by Penny2312** [comment]
> > > Look for where ani-cli looks for mpv. Have you checked the location ?
> > 
> > 
> > How to check that?
> 
> Search "edit the system environment variables" in windows search bar, should open something like this: ![image](https://user-images.githubusercontent.com/53411412/209912573-f3070d9a-068b-4cac-a0bf-09b87f0cdcea.png) Then click environment variables and search for the variable called "Path" and click on it. If the folder location for mpv is there, it should be all right. However I am having the same problem and mpv was added in $PATH by scoop.

So I had the same issue and found out `mpv.exe` was not in my `C:\Users\USERNAME\scoop\shims` file ()which is in my Path). I looked for `mpv.exe` inside the `apps` folder (`C:\Users\USERNAME\scoop\apps\ani-cli\4.10`)where it actually is, then copied it into the `shims` file where the other .exe files are. this worked for me right away! Hope this helps others.
